export const SPECIALITES = [
"Anatomie générale",
"Anatomie normale",
"Anatomie -Pathologique",
"Anesthésie-Réanimation",
"Anesthésie Réanimation pédiatrique",
"Biochimie",
"Biologie clinique",
"Biophysique",
"Cardiologie",
"Chirurgie Cardio-Vasculaire",
"Chirurgie Générale",
"Chirurgie maxillo-Faciale",
"Chirurgie Orthopédique",
"Chirurgie Pédiatrique",
"Chirurgie plastique reconstructrice Esthétique et de Brûlogie",
"Chirurgie Urologique",
"Dermatologie",
"Dermatologie et Vénéréologie",
"Diabétologie – Endocrinologie et Maladies Métaboliques",
"Endocrinologie",
"Épidémiologie",
"Gastro-entérologie",
"Gynéco-Obstétrique",
"Hématologie",
"Hémobiologie",
"Histologie-embryologie et génétique",
"Immunologie",
"Maladies infectieuses",
"Médecine du sport",
"Médecine du travail",
"Médecine Interne",
"Médecine Légale",
"Médecine Nucléaire",
"Microbiologie",
"Néphrologie",
"Neurochirurgie",
"Neurologie",
"Ophtalmologie",
"O.R.L.",
"Oncologie Médicale",
"Parasitologie",
"Pédiatrie",
"Pharmacologie clinique",
"Physiologie",
"Pneumo-Phtisiologie",
"Psychiatrie",
"Radiodiagnostic",
"radiologie",
"Radiothérapie",
"Rééducation - Fonctionnelle",
"Rhumatologie",
];
